channels:
- conda-forge
dependencies:
- python=3.11.7
- pip<=23.3.1
- pip:
  - mlflow==2.13.0
  - cloudpickle==2.2.1
  - lz4==4.3.2
  - pathlib==1.0.1
  - psutil==5.9.0
  - scikit-learn==1.2.2
name: mlflow-env
